### ISSUE TITLE
Fixed numpy version

### ISSUE THREAD

**Issue by kapoorlab** [Sentinal4D/cellshape-cloud#13]
**Describe the bug**
The numpy version is fixed in the setup file, maybe it could be specified to be a version greater than the fixed specified version or is there a reason to hard fix it?

**To Reproduce**
See the fixed version number in the setup file

**Expected behavior**
To specify a version greater than a certain version, this can lead to unexpected behaviour like rolling a numpy version in the environment by uninstalling the installed numpy versi.

**Comment by DeVriesMatt** [comment]
The commit [84ec1be](https://github.com/Sentinal4D/cellshape-cloud/commit/84ec1bed0b2d8dcecafaf30a987c693863b5cf3c) solves the issue.
